from dictshield.document import Document
from dictshield.fields import (IntField,
                               StringField,
                               EmailField,
                               ObjectIdField)

from arbre.timestamping import MillisecondField
from arbre.models import EmailEdge, Email


###
### Document designs
###
        
    
class MaildirEmail(Email):
    """Maps the structure generated from Python's email module into a document
    by extending `Email`.
    """
    SOURCE_NAME = 'maildir'
    
    source = StringField(required=True, default=SOURCE_NAME)

    ### Maildir variations
    content_type = StringField()
    mime_version = StringField()
    content_transfer_encoding = StringField()
    attendees = StringField()
    time = StringField()

    @classmethod
    def gen_from_message(cls, msg):
        """Generates an Email instance from the msg generated by
        `email.message_from_file`.
        """
        contents = cls.headermap_from_list(msg._headers)
        contents['body'] = msg._payload
        return cls(**contents)

    

    
class LuceneEmail(Email):
    """Maps the structure generated from Python's email module into a document
    by extending `Email`.
    """
    SOURCE_NAME = 'lucene'

    source = StringField(required=True, default=SOURCE_NAME)

    # Trust 'fromName' in lucene more than 'x-from'    
    dirty_x_from = StringField() 
    dirty_x_to = StringField()

    ### Meta fields
    quoted_lines = StringField()
    quoted_type = StringField()
    unstemmed_contents = StringField()
    num_quoted = StringField()
    length = StringField()
    contents = StringField()
    contents_lines = StringField()

